model_name: "/data1/yx/plm/LLM-Research/gemma-3-1b-it"
learning_rate: 0.000005  # 从 5e-6 改为这个值
epochs_stage_1: 2
epochs_stage_2: 3
beta_kl: 0.01  # 从 0.1 改为 0.01
alpha: 0.5  # 从 1.0 改为 0.5
data_file: "/data1/yx/score/Google_SCoRe/SCoRe_Dasetset_complete_translated.csv"
warmup_steps: 100  # 新增项
max_grad_norm: 1.0  # 新增项
